### ISSUE TITLE
tern无效

### ISSUE THREAD

**Issue by SaneBow** [chemzqm/wxapp.vim#3]
尝试按照最新的README配置流程：
1. 在tern_for_vim目录执行npm install
2. 拷贝wxapp.json到小程序项目目录的父目录
3. 在小程序项目目录创建.tern-project

进入vim无效果。

若第一步用npm install -g tern

然后在.tern-project同目录执行tern，返回错误信息如下
`/usr/local/lib/node_modules/tern/lib/def.js:85
      throw new Error("Unrecognized type spec: " + this.spec + " (at " + this.pos + ")");
      ^

Error: Unrecognized type spec: fn({url: string, data: object, header: object, method: string, dataType: string, success: fn(res: object), fail: fn(res: object)}) (at 3)
    at exports.TypeParser.error (/usr/local/lib/node_modules/tern/lib/def.js:85:13)
    at exports.TypeParser.parseFnType (/usr/local/lib/node_modules/tern/lib/def.js:103:33)
    at exports.TypeParser.parseTypeInner (/usr/local/lib/node_modules/tern/lib/def.js:160:21)
    at exports.TypeParser.parseTypeMaybeProp (/usr/local/lib/node_modules/tern/lib/def.js:146:25)
    at exports.TypeParser.parseType (/usr/local/lib/node_modules/tern/lib/def.js:130:23)
    at parseType (/usr/local/lib/node_modules/tern/lib/def.js:262:59)
    at passTwo (/usr/local/lib/node_modules/tern/lib/def.js:424:9)
    at passTwo (/usr/local/lib/node_modules/tern/lib/def.js:442:11)
    at passTwo (/usr/local/lib/node_modules/tern/lib/def.js:442:11)
    at doLoadEnvironment (/usr/local/lib/node_modules/tern/lib/def.js:484:5)`

求教正确的配置方法？

**Comment by chemzqm** [comment]
@SaneBow 感谢反馈，tern 的 npm 发行版暂时不支持这个语法，所以导致无法实现函数参数属性名补全，master 分支的 tern 已经修复了这个问题，需要 tern 那边发布最新版解决这个问题。

你可以把 https://github.com/ternjs/tern master 分支 clone 到本地，安装后使用 `./bin/tern` 启用 tern 服务。

**Comment by SaneBow** [comment]
原来是这样，好的多谢了

**Comment by chemzqm** [comment]
更新了文档， 推荐使用 npm install https://github.com/ternjs/tern/tarball/master 方式安装。

**Comment by SaneBow** [comment]
我手动替换了最新的tern，可以正常使用了，万分感谢
